### ISSUE TITLE
Error when a web layer is in the map

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/qaequilibrae#10]
An example of error is the following: 
Traceback (most recent call last):
              File "C:/Users/pedro.camargo.VEITCHLISTER/.qgis2/python/plugins\AequilibraE\AequilibraEMenu.py", line 277, in run_dlines
                dlg2 = DesireLinesDialog(self.iface)
              File "C:/Users/pedro.camargo.VEITCHLISTER/.qgis2/python/plugins\AequilibraE\desire_lines_dialog.py", line 63, in **init**
                if layer.wkbType() in poly_types or layer.wkbType() in point_types:
            AttributeError: 'QgsRasterLayer' object has no attribute 'wkbType'

**Comment by pedrocamargo** [comment]
Fixed on version 0.32

Commit: 62bf711f03150bc0ed3809f4634a943e9b5a4315
