### ISSUE TITLE
Least Commom Denominator does not load

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/qaequilibrae#11]
2016-10-16T07:34:18 1   Traceback (most recent call last):
              File "C:/Users/Pedro/.qgis2/python/plugins\AequilibraE\AequilibraEMenu.py", line 272, in run_lcd
                dlg2 = LeastCommonDenominatorDialog(self.iface)
              File "C:/Users/Pedro/.qgis2/python/plugins\AequilibraE\least_common_denominator_dialog.py", line 50, in **init**
                self.from_layer.currentIndexChanged.connect(partial(self.reload_fields, 'from'))
            AttributeError: 'LeastCommonDenominatorDialog' object has no attribute 'from_layer'

Error probably comming from a disconnect between the UI as done in designer and the dialog class that uses it.

**Comment by pedrocamargo** [comment]
Fixed with a commit: 6249e26702df7fa743c929227a06a927ee864e8b
