### ISSUE TITLE
[BUG] Affectation error : "ValueError: cost_field not available in the graph"

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/qaequilibrae#187]
Was conducting more tests on new GUI version (used project with dumb demand, capacity, speed, etc: [St_Varent.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/8583798/St_Varent.zip)) : 
- OSM importing -> ❤️ 
- Network editing to add centoids and complete fileds -> Great 👍 (except for the small locked database bug)
- Importing demand matrix from an excel with dumb values -> perfect 🔥 
- Shortest path tests -> fluid 💯  
- Assignment with BPR (default 0.15 and 4 parameters)... errors ! ( just before the finish line 🏁 )

<details>

	  ValueError: cost_field not available in the graph:Index(['link_id', 'a_node', 'b_node', 'direction', 'id', 'distance', 'speed',       'capacity', 'osm_id', 'lanes', 'modes', '__supernet_id__',       '__compressed_id__'],       dtype='object') 
	  Traceback (most recent call last):
	    File "%qgisProfile%/python/plugins\AequilibraE\paths_procedures\traffic_assignment_dialog.py", line 357, in run
	      if not self.check_data():
	    File "%qgisProfile%/python/plugins\AequilibraE\paths_procedures\traffic_assignment_dialog.py", line 405, in check_data
	      tries_setup = self.set_assignment()
	    File "%qgisProfile%/python/plugins\AequilibraE\paths_procedures\traffic_assignment_dialog.py", line 456, in set_assignment
	      cls.graph.set_graph(self.cob_ffttime.currentText())
	    File "%qgisProfile%\python\plugins\AequilibraE\aequilibrae\aequilibrae\paths\graph.py", line 455, in set_graph
	      raise ValueError("cost_field not available in the graph:" + str(self.graph.columns))
	  ValueError: cost_field not available in the graph:Index(['link_id', 'a_node', 'b_node', 'direction', 'id', 'distance', 'speed',
	         'capacity', 'osm_id', 'lanes', 'modes', '__supernet_id__',
	         '__compressed_id__'],
	        dtype='object')

</details>

**Comment by Art-Ev** [comment]
My bad it was a stupid user error (user=me)
