### ISSUE TITLE
Uncaught FileNotFoundError: [Errno 2] No such file or directory: ''


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [AequilibraE/qaequilibrae#207]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\AequilibraE\project_procedures\project_from_osm_dialog.py", line 204, in signal_downloader_handler
    self.final_steps()
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\AequilibraE\project_procedures\project_from_osm_dialog.py", line 164, in final_steps
    self.project = Project(self.output_path.text(), True)
  File "C:\Users\Lucio De Benedictis\AppData\Roaming\QGIS\QGIS3\profiles\Lucio_02_23\python\plugins\AequilibraE\aequilibrae\aequilibrae\project\project.py", line 22, in __init__
    self.__create_empty_project()
  File "C:\Users\Lucio De Benedictis\AppData\Roaming\QGIS\QGIS3\profiles\Lucio_02_23\python\plugins\AequilibraE\aequilibrae\aequilibrae\project\project.py", line 31, in __create_empty_project
    shutil.copyfile(spatialite_database, self.path_to_file)
  File "C:\OSGeo4W\apps\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: ''

```
AequilibraE 0.6.2, QGIS 3.28.4-Firenze on Windows 10

**Comment by jamiecook** [comment]
Hi Lucio, it's quite hard to provide any help without details of what you were acutally trying to do when you ran into this problem. 
My first suggestion would be to upgrade to a more recent version of the package - if you still experience this - please fill the 1/2/3 above to show us how to reproduce the problem.

**Comment by pedrocamargo** [comment]
Version 0.6.2 is no longer supported, so closing the issue
